const { withAppBuildGradle } = require('expo/config-plugins');

const LEGACY_MARKER = '// @generated by withReleaseSigning';
const BEGIN_MARKER = '// @generated begin withReleaseSigning';
const END_MARKER = '// @generated end withReleaseSigning';

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error(`withReleaseSigning requires Groovy build.gradle, got ${cfg.modResults.language}`);
    }
    let source = cfg.modResults.contents;

    const definitions = `${BEGIN_MARKER}
def releaseKeystoreFile = System.getenv('ANDROID_KEYSTORE_FILE')
def releaseKeystorePassword = System.getenv('ANDROID_KEYSTORE_PASSWORD')
def releaseKeyAlias = System.getenv('ANDROID_KEY_ALIAS')
def releaseKeyPassword = System.getenv('ANDROID_KEY_PASSWORD')
def releaseVersionCode = System.getenv('ANDROID_VERSION_CODE')
def releaseSigningConfigured = [releaseKeystoreFile, releaseKeystorePassword, releaseKeyAlias, releaseKeyPassword].every { it != null && !it.trim().isEmpty() }
if (releaseVersionCode != null && !(releaseVersionCode ==~ /[1-9][0-9]*/)) {
    throw new GradleException('ANDROID_VERSION_CODE must be a positive integer')
}
def resolvedVersionCode = releaseVersionCode == null || releaseVersionCode.trim().isEmpty() ? 1 : releaseVersionCode.toInteger()
gradle.taskGraph.whenReady { graph ->
    def releaseTaskInGraph = graph.allTasks.any { task ->
        task.project == project && task.name.toLowerCase().contains('release')
    }
    if (releaseTaskInGraph && (!releaseSigningConfigured || releaseVersionCode == null || releaseVersionCode.trim().isEmpty())) {
        throw new GradleException('Release tasks require ANDROID_KEYSTORE_FILE, ANDROID_KEYSTORE_PASSWORD, ANDROID_KEY_ALIAS, ANDROID_KEY_PASSWORD, and ANDROID_VERSION_CODE')
    }
}
${END_MARKER}

`;
    const androidAnchor = 'android {\n';
    if (!source.includes(androidAnchor)) {
      throw new Error('withReleaseSigning: android block not found in app/build.gradle');
    }

    const begin = source.indexOf(BEGIN_MARKER);
    if (begin !== -1) {
      const end = source.indexOf(END_MARKER, begin);
      if (end === -1) throw new Error('withReleaseSigning: generated block has no end marker');
      source = source.slice(0, begin) + definitions + source.slice(end + END_MARKER.length + 1);
      cfg.modResults.contents = source;
      return cfg;
    }

    const legacy = source.indexOf(LEGACY_MARKER);
    if (legacy !== -1) {
      const android = source.indexOf(androidAnchor, legacy);
      if (android === -1) throw new Error('withReleaseSigning: legacy block has no android block');
      source = source.slice(0, legacy) + definitions + source.slice(android);
      cfg.modResults.contents = source;
      return cfg;
    }

    source = source.replace(androidAnchor, `${definitions}${androidAnchor}`);
    source = source.replace(
      '        versionCode 1\n',
      '        versionCode resolvedVersionCode\n',
    );

    const signingAnchor = `        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
`;
    if (!source.includes(signingAnchor)) {
      throw new Error('withReleaseSigning: debug signing block not found in app/build.gradle');
    }
    source = source.replace(
      signingAnchor,
      `${signingAnchor}        if (releaseSigningConfigured) {
            release {
                storeFile file(releaseKeystoreFile)
                storePassword releaseKeystorePassword
                keyAlias releaseKeyAlias
                keyPassword releaseKeyPassword
            }
        }
`,
    );

    const unsafeReleaseSigning = '            signingConfig signingConfigs.debug\n';
    const buildTypesBlock = source.indexOf('    buildTypes {');
    const releaseBlock = source.indexOf('        release {', buildTypesBlock);
    const unsafeSigning = source.indexOf(unsafeReleaseSigning, releaseBlock);
    if (buildTypesBlock === -1 || releaseBlock === -1 || unsafeSigning === -1) {
      throw new Error('withReleaseSigning: unsafe release debug-signing line not found');
    }
    source =
      source.slice(0, unsafeSigning) +
      `            if (releaseSigningConfigured) {
                signingConfig signingConfigs.release
            }
` +
      source.slice(unsafeSigning + unsafeReleaseSigning.length);

    cfg.modResults.contents = source;
    return cfg;
  });
};
