import { createRuntimeCatalog, type AppLocale } from '../localization';

const catalogs = {
  de: {
    common: {
      retry: 'Erneut versuchen',
      refreshing: 'Wird aktualisiert …',
      stale: 'Gespeicherte Daten – zum Aktualisieren nach unten ziehen.',
      offline: 'Du bist offline. Stelle eine Verbindung her und versuche es erneut.',
      loadFailed: 'Daten konnten nicht geladen werden. Versuche es erneut.',
      cachedOffline: 'Du bist offline. Gespeicherte Daten werden angezeigt.',
      cachedRefreshFailed: 'Aktualisierung fehlgeschlagen. Gespeicherte Daten werden angezeigt.',
      tracks: (count: number) => `${count} ${count === 1 ? 'Titel' : 'Titel'}`,
      playbackFailed: 'Wiedergabe fehlgeschlagen',
      cancel: 'Abbrechen',
      save: 'Speichern',
      saving: 'Wird gespeichert …',
    },
    library: {
      title: 'Deine Mediathek',
      subtitle: 'Playlists, Favoriten und deine persönliche Hörhistorie an einem Ort.',
      playlists: 'Playlists',
      likedTracks: 'Lieblingstitel',
      recentlyHeard: 'Zuletzt gehört',
      downloads: 'Downloads',
      following: 'Gefolgte Künstler:innen',
      refreshAll: 'Mediathek aktualisieren',
      loadingSection: (title: string) => `${title} werden geladen …`,
      retrySection: (title: string) => `${title} erneut laden`,
      noPlaylists: 'Du hast noch keine Playlist erstellt.',
      noLikes: 'Du hast noch keine Titel als Favorit markiert.',
      noRecent: 'Deine zuletzt gehörten Titel erscheinen hier.',
      noFollowing: 'Du folgst noch keinen Künstler:innen.',
      downloadsLoading: 'Offline-Downloads werden geladen …',
      downloadsUnavailable: 'Offline-Downloads nicht verfügbar',
      downloadsUnavailableBody:
        'Der geschützte Offline-Speicher konnte nicht geöffnet werden.',
      noDownloads: 'Noch keine Offline-Downloads',
      noDownloadsBody: 'Öffne eine Playlist, um sie für die Offline-Wiedergabe zu speichern.',
      downloadedPlaylist: (downloaded: number, total: number) =>
        `${downloaded} von ${total} Titeln heruntergeladen`,
      partialDownload: (downloaded: number, total: number, failed: number) =>
        `${downloaded} von ${total} Titeln heruntergeladen, ${failed} fehlgeschlagen`,
      openDownload: (name: string, downloaded: number, total: number) =>
        `${name} öffnen, ${downloaded} von ${total} Titeln heruntergeladen`,
      createPlaylist: 'Playlist erstellen',
      createTitle: 'Neue Playlist',
      name: 'Name',
      description: 'Beschreibung (optional)',
      creating: 'Wird erstellt …',
      createFailed: 'Die Playlist konnte nicht erstellt werden.',
      created: (name: string) => `Playlist „${name}“ wurde erstellt.`,
      openPlaylist: (name: string, count: number) => `${name}, ${count} Titel öffnen`,
      openLiked: (count: number) => `Lieblingstitel öffnen, ${count} Titel`,
      openAlbum: (title: string, artist: string) => `Album ${title} von ${artist} öffnen`,
      openArtist: (name: string) => `${name} öffnen`,
      playTrack: (title: string, artist: string) => `${title} von ${artist} abspielen`,
    },
    playlist: {
      loading: 'Playlist wird geladen …',
      noTracks: 'Diese Playlist enthält noch keine Titel.',
      playAll: 'Alle abspielen',
      edit: 'Bearbeiten',
      editTitle: 'Playlist bearbeiten',
      public: 'Öffentlich',
      private: 'Privat',
      makePublic: 'Playlist veröffentlichen',
      makePrivate: 'Playlist privat machen',
      delete: 'Playlist löschen',
      deleteTitle: 'Playlist wirklich löschen?',
      deleteMessage: (name: string) => `„${name}“ und ihre Zusammenstellung werden dauerhaft gelöscht.`,
      deleteConfirm: 'Löschen',
      ownerOnly: 'Nur der oder die Eigentümer:in kann diese Playlist bearbeiten.',
      byOwner: (name: string) => `Von ${name}`,
      remove: (title: string) => `${title} aus der Playlist entfernen`,
      moveUp: (title: string) => `${title} nach oben verschieben`,
      moveDown: (title: string) => `${title} nach unten verschieben`,
      mutationInProgress: 'Änderung wird gespeichert …',
      mutationFailed: 'Die Änderung konnte nicht gespeichert werden.',
      actionFailed: 'Die Aktion konnte nicht abgeschlossen werden.',
      nameRequired: 'Gib einen Playlist-Namen ein.',
      localCopy: 'Offline-Kopie. Nur heruntergeladene Titel werden ohne Verbindung abgespielt.',
      localTrackUnavailable: 'Dieser Titel ist in der Offline-Kopie nicht verfügbar.',
      offlineUnavailable: 'Offline-Downloads werden vorbereitet oder sind nicht verfügbar.',
      offlineIdle: 'Diese Playlist für die Offline-Wiedergabe speichern.',
      offlineDownloading: (downloaded: number, total: number) =>
        `Wird heruntergeladen: ${downloaded} von ${total} Titeln sind verfügbar.`,
      offlinePartial: (downloaded: number, total: number, failed: number) =>
        `${downloaded} von ${total} Titeln gespeichert; ${failed} fehlgeschlagen.`,
      offlineDownloaded: (downloaded: number, total: number) =>
        `${downloaded} von ${total} Titeln heruntergeladen.`,
      offlineRemoving: (removed: number, total: number) =>
        `Downloads werden entfernt: ${removed} von ${total}.`,
      offlineError: (downloaded: number) =>
        `Download fehlgeschlagen; ${downloaded} Titel bleiben verfügbar.`,
      offlineRemoveError:
        'Der Offline-Download konnte nicht vollständig entfernt werden. Versuche das Entfernen erneut.',
      offlineProgress: (percent: number) => `${percent} Prozent`,
      downloadAction: 'Herunterladen',
      downloadingAction: 'Wird heruntergeladen',
      retryDownloadAction: 'Download erneut versuchen',
      removeDownloadAction: 'Download entfernen',
      removingDownloadAction: 'Wird entfernt',
    },
  },
  en: {
    common: {
      retry: 'Try again',
      refreshing: 'Refreshing…',
      stale: 'Showing saved data — pull down to refresh.',
      offline: 'You are offline. Connect and try again.',
      loadFailed: 'Data could not be loaded. Try again.',
      cachedOffline: 'You are offline. Showing saved data.',
      cachedRefreshFailed: 'Refresh failed. Showing saved data.',
      tracks: (count: number) => `${count} ${count === 1 ? 'track' : 'tracks'}`,
      playbackFailed: 'Playback failed',
      cancel: 'Cancel',
      save: 'Save',
      saving: 'Saving…',
    },
    library: {
      title: 'Your Library',
      subtitle: 'Playlists, favorites, and your listening history in one place.',
      playlists: 'Playlists',
      likedTracks: 'Liked Tracks',
      recentlyHeard: 'Recently Heard',
      downloads: 'Downloads',
      following: 'Following',
      refreshAll: 'Refresh Library',
      loadingSection: (title: string) => `Loading ${title}…`,
      retrySection: (title: string) => `Retry ${title}`,
      noPlaylists: 'You have not created a playlist yet.',
      noLikes: 'You have not liked any tracks yet.',
      noRecent: 'Tracks you listen to will appear here.',
      noFollowing: 'You are not following any artists yet.',
      downloadsLoading: 'Loading offline downloads…',
      downloadsUnavailable: 'Offline downloads unavailable',
      downloadsUnavailableBody:
        'The protected offline storage could not be opened.',
      noDownloads: 'No offline downloads yet',
      noDownloadsBody: 'Open a playlist to save it for offline playback.',
      downloadedPlaylist: (downloaded: number, total: number) =>
        `${downloaded} of ${total} tracks downloaded`,
      partialDownload: (downloaded: number, total: number, failed: number) =>
        `${downloaded} of ${total} tracks downloaded, ${failed} failed`,
      openDownload: (name: string, downloaded: number, total: number) =>
        `Open ${name}, ${downloaded} of ${total} tracks downloaded`,
      createPlaylist: 'Create playlist',
      createTitle: 'New playlist',
      name: 'Name',
      description: 'Description (optional)',
      creating: 'Creating…',
      createFailed: 'The playlist could not be created.',
      created: (name: string) => `Playlist ${name} was created.`,
      openPlaylist: (name: string, count: number) => `Open ${name}, ${count} tracks`,
      openLiked: (count: number) => `Open liked tracks, ${count} tracks`,
      openAlbum: (title: string, artist: string) => `Open album ${title} by ${artist}`,
      openArtist: (name: string) => `Open ${name}`,
      playTrack: (title: string, artist: string) => `Play ${title} by ${artist}`,
    },
    playlist: {
      loading: 'Loading playlist…',
      noTracks: 'This playlist does not contain any tracks yet.',
      playAll: 'Play all',
      edit: 'Edit',
      editTitle: 'Edit playlist',
      public: 'Public',
      private: 'Private',
      makePublic: 'Make playlist public',
      makePrivate: 'Make playlist private',
      delete: 'Delete playlist',
      deleteTitle: 'Delete playlist?',
      deleteMessage: (name: string) => `“${name}” and its ordering will be permanently deleted.`,
      deleteConfirm: 'Delete',
      ownerOnly: 'Only the owner can edit this playlist.',
      byOwner: (name: string) => `By ${name}`,
      remove: (title: string) => `Remove ${title} from the playlist`,
      moveUp: (title: string) => `Move ${title} up`,
      moveDown: (title: string) => `Move ${title} down`,
      mutationInProgress: 'Saving change…',
      mutationFailed: 'The change could not be saved.',
      actionFailed: 'The action could not be completed.',
      nameRequired: 'Enter a playlist name.',
      localCopy: 'Offline copy. Only downloaded tracks play without a connection.',
      localTrackUnavailable: 'This track is not available in the offline copy.',
      offlineUnavailable: 'Offline downloads are being prepared or are unavailable.',
      offlineIdle: 'Save this playlist for offline playback.',
      offlineDownloading: (downloaded: number, total: number) =>
        `Downloading: ${downloaded} of ${total} tracks are available.`,
      offlinePartial: (downloaded: number, total: number, failed: number) =>
        `${downloaded} of ${total} tracks saved; ${failed} failed.`,
      offlineDownloaded: (downloaded: number, total: number) =>
        `${downloaded} of ${total} tracks downloaded.`,
      offlineRemoving: (removed: number, total: number) =>
        `Removing downloads: ${removed} of ${total}.`,
      offlineError: (downloaded: number) =>
        `Download failed; ${downloaded} tracks remain available.`,
      offlineRemoveError:
        'The offline download could not be fully removed. Try removing it again.',
      offlineProgress: (percent: number) => `${percent} percent`,
      downloadAction: 'Download',
      downloadingAction: 'Downloading',
      retryDownloadAction: 'Retry download',
      removeDownloadAction: 'Remove download',
      removingDownloadAction: 'Removing',
    },
  },
} satisfies Record<AppLocale, object>;

export const libraryStrings = createRuntimeCatalog(catalogs);
